# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Raju Kalidindi
email: krkraju997@gmail.com
username: Raju Kalidindi
user_title: Software Engineer
description: >
  Hello, I'm Ramana Krishnam Raju Kalidindi, a passionate Software Engineer based in Bristol. I hold a Master's degree in Computing Science from the University of Glasgow and a Bachelor's degree in Computer Science from the International Institute of Information Technology, Bhubaneswar.
  <br><br>
  With extensive experience in web and mobile development, I have worked with technologies like React, TypeScript, AWS, Laravel, Python, and GraphQL. I have a solid foundation in Android development and have designed responsive user interfaces using Angular.
  <br><br>
  My interests span across virtual reality, game development, augmented reality, and front-end development. Outside of work, I enjoy traveling, cooking, playing cricket and football, and I'm a dedicated Real Madrid supporter.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: RajuKalidindi

# Build settings
sass:
  sass_dir: _sass
include: ["_pages"]
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
